/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_Ocl_ErrorMessages */

#ifndef _Included_ocl_Ocl_ErrorMessages
#define _Included_ocl_Ocl_ErrorMessages
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
