/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_Ocl */

#ifndef _Included_ocl_Ocl
#define _Included_ocl_Ocl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ocl_Ocl
 * Method:    Open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_Ocl_Open
  (JNIEnv *, jobject);

/*
 * Class:     ocl_Ocl
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_Ocl_Close
  (JNIEnv *, jobject);

/*
 * Class:     ocl_Ocl
 * Method:    OclFilter
 * Signature: ([Ljava/lang/Character;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclFilter___3Ljava_lang_Character_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclFilter
 * Signature: ([Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclFilter___3Ljava_lang_Integer_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclFilter
 * Signature: ([Ljava/lang/Double;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclFilter___3Ljava_lang_Double_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToCharArray
 * Signature: ([Ljava/lang/Character;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToCharArray___3Ljava_lang_Character_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToCharArray
 * Signature: ([Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToCharArray___3Ljava_lang_Integer_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToCharArray
 * Signature: ([Ljava/lang/Double;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToCharArray___3Ljava_lang_Double_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToIntArray
 * Signature: ([Ljava/lang/Character;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToIntArray___3Ljava_lang_Character_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToIntArray
 * Signature: ([Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToIntArray___3Ljava_lang_Integer_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToIntArray
 * Signature: ([Ljava/lang/Double;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToIntArray___3Ljava_lang_Double_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToDoubleArray
 * Signature: ([Ljava/lang/Character;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToDoubleArray___3Ljava_lang_Character_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToDoubleArray
 * Signature: ([Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToDoubleArray___3Ljava_lang_Integer_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMapToDoubleArray
 * Signature: ([Ljava/lang/Double;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMapToDoubleArray___3Ljava_lang_Double_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclSample
 * Signature: ([Ljava/lang/Character;ZF)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclSample___3Ljava_lang_Character_2ZF
  (JNIEnv *, jobject, jobjectArray, jboolean, jfloat);

/*
 * Class:     ocl_Ocl
 * Method:    OclSample
 * Signature: ([Ljava/lang/Integer;ZF)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclSample___3Ljava_lang_Integer_2ZF
  (JNIEnv *, jobject, jobjectArray, jboolean, jfloat);

/*
 * Class:     ocl_Ocl
 * Method:    OclSample
 * Signature: ([Ljava/lang/Double;ZF)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclSample___3Ljava_lang_Double_2ZF
  (JNIEnv *, jobject, jobjectArray, jboolean, jfloat);

/*
 * Class:     ocl_Ocl
 * Method:    OclSample
 * Signature: ([Ljava/lang/Character;ZFI)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclSample___3Ljava_lang_Character_2ZFI
  (JNIEnv *, jobject, jobjectArray, jboolean, jfloat, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclSample
 * Signature: ([Ljava/lang/Integer;ZFI)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclSample___3Ljava_lang_Integer_2ZFI
  (JNIEnv *, jobject, jobjectArray, jboolean, jfloat, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclSample
 * Signature: ([Ljava/lang/Double;ZFI)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclSample___3Ljava_lang_Double_2ZFI
  (JNIEnv *, jobject, jobjectArray, jboolean, jfloat, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclUnion
 * Signature: ([Ljava/lang/Character;[Ljava/lang/Character;)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclUnion___3Ljava_lang_Character_2_3Ljava_lang_Character_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclUnion
 * Signature: ([Ljava/lang/Integer;[Ljava/lang/Integer;)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclUnion___3Ljava_lang_Integer_2_3Ljava_lang_Integer_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclUnion
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclUnion___3Ljava_lang_Double_2_3Ljava_lang_Double_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclIntersection
 * Signature: ([Ljava/lang/Character;[Ljava/lang/Character;)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclIntersection___3Ljava_lang_Character_2_3Ljava_lang_Character_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclIntersection
 * Signature: ([Ljava/lang/Integer;[Ljava/lang/Integer;)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclIntersection___3Ljava_lang_Integer_2_3Ljava_lang_Integer_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclIntersection
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclIntersection___3Ljava_lang_Double_2_3Ljava_lang_Double_2
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclTake
 * Signature: ([Ljava/lang/Character;I)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTake___3Ljava_lang_Character_2I
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTake
 * Signature: ([Ljava/lang/Integer;I)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTake___3Ljava_lang_Integer_2I
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTake
 * Signature: ([Ljava/lang/Double;I)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTake___3Ljava_lang_Double_2I
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTakeSample
 * Signature: ([Ljava/lang/Character;ZI)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTakeSample___3Ljava_lang_Character_2ZI
  (JNIEnv *, jobject, jobjectArray, jboolean, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTakeSample
 * Signature: ([Ljava/lang/Integer;ZI)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTakeSample___3Ljava_lang_Integer_2ZI
  (JNIEnv *, jobject, jobjectArray, jboolean, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTakeSample
 * Signature: ([Ljava/lang/Double;ZI)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTakeSample___3Ljava_lang_Double_2ZI
  (JNIEnv *, jobject, jobjectArray, jboolean, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTakeSample
 * Signature: ([Ljava/lang/Character;ZII)[Ljava/lang/Character;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTakeSample___3Ljava_lang_Character_2ZII
  (JNIEnv *, jobject, jobjectArray, jboolean, jint, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTakeSample
 * Signature: ([Ljava/lang/Integer;ZII)[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTakeSample___3Ljava_lang_Integer_2ZII
  (JNIEnv *, jobject, jobjectArray, jboolean, jint, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTakeSample
 * Signature: ([Ljava/lang/Double;ZII)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclTakeSample___3Ljava_lang_Double_2ZII
  (JNIEnv *, jobject, jobjectArray, jboolean, jint, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclReduce
 * Signature: ([Ljava/lang/Character;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Character;
 */
JNIEXPORT jobject JNICALL Java_ocl_Ocl_OclReduce___3Ljava_lang_Character_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclReduce
 * Signature: ([Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_ocl_Ocl_OclReduce___3Ljava_lang_Integer_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclReduce
 * Signature: ([Ljava/lang/Double;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_ocl_Ocl_OclReduce___3Ljava_lang_Double_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
