/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_Ocl */

#ifndef _Included_ocl_Ocl
#define _Included_ocl_Ocl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ocl_Ocl
 * Method:    Open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_Ocl_Open
  (JNIEnv *, jobject);

/*
 * Class:     ocl_Ocl
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_Ocl_Close
  (JNIEnv *, jobject);

/*
 * Class:     ocl_Ocl
 * Method:    OclMap
 * Signature: ([[BLjava/lang/String;Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_ocl_Ocl_OclMap___3_3BLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMap
 * Signature: ([ILjava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_Ocl_OclMap___3ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jintArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclMap
 * Signature: ([DLjava/lang/String;Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ocl_Ocl_OclMap___3DLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jdoubleArray, jstring, jstring);

/*
 * Class:     ocl_Ocl
 * Method:    OclUnion
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_Ocl_OclUnion___3I_3I
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclUnion
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ocl_Ocl_OclUnion___3D_3D
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     ocl_Ocl
 * Method:    OclTake
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_Ocl_OclTake___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     ocl_Ocl
 * Method:    OclTake
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ocl_Ocl_OclTake___3DI
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
