/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_IntArrayOCLCommandRunner */

#ifndef _Included_ocl_IntArrayOCLCommandRunner
#define _Included_ocl_IntArrayOCLCommandRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclFilter
 * Signature: ([ILjava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclFilter
  (JNIEnv *, jobject, jintArray, jstring, jstring);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclMap
 * Signature: ([ILjava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclMap
  (JNIEnv *, jobject, jintArray, jstring, jstring);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclSample
 * Signature: ([IZF)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclSample___3IZF
  (JNIEnv *, jobject, jintArray, jboolean, jfloat);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclSample
 * Signature: ([IZFI)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclSample___3IZFI
  (JNIEnv *, jobject, jintArray, jboolean, jfloat, jint);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclUnion
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclUnion
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclIntersection
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclIntersection
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclTake
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclTake
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclTakeSample
 * Signature: ([IZI)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclTakeSample___3IZI
  (JNIEnv *, jobject, jintArray, jboolean, jint);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclTakeSample
 * Signature: ([IZII)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_IntArrayOCLCommandRunner_OclTakeSample___3IZII
  (JNIEnv *, jobject, jintArray, jboolean, jint, jint);

/*
 * Class:     ocl_IntArrayOCLCommandRunner
 * Method:    OclReduce
 * Signature: ([ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ocl_IntArrayOCLCommandRunner_OclReduce
  (JNIEnv *, jobject, jintArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
