/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_DataConverter */

#ifndef _Included_ocl_DataConverter
#define _Included_ocl_DataConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ocl_DataConverter
 * Method:    toIntArray
 * Signature: ([CLjava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_DataConverter_toIntArray___3CLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jcharArray, jstring, jstring);

/*
 * Class:     ocl_DataConverter
 * Method:    toIntArray
 * Signature: ([DLjava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_ocl_DataConverter_toIntArray___3DLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jdoubleArray, jstring, jstring);

/*
 * Class:     ocl_DataConverter
 * Method:    toCharArray
 * Signature: ([ILjava/lang/String;Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_ocl_DataConverter_toCharArray___3ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jintArray, jstring, jstring);

/*
 * Class:     ocl_DataConverter
 * Method:    toCharArray
 * Signature: ([DLjava/lang/String;Ljava/lang/String;)[C
 */
JNIEXPORT jcharArray JNICALL Java_ocl_DataConverter_toCharArray___3DLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jdoubleArray, jstring, jstring);

/*
 * Class:     ocl_DataConverter
 * Method:    toDoubleArray
 * Signature: ([ILjava/lang/String;Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ocl_DataConverter_toDoubleArray___3ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jintArray, jstring, jstring);

/*
 * Class:     ocl_DataConverter
 * Method:    toDoubleArray
 * Signature: ([CLjava/lang/String;Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ocl_DataConverter_toDoubleArray___3CLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jcharArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
