/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oclBridge_AbstractOclBridge */

#ifndef _Included_oclBridge_AbstractOclBridge
#define _Included_oclBridge_AbstractOclBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oclBridge_AbstractOclBridge
 * Method:    Initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_oclBridge_AbstractOclBridge_Initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     oclBridge_AbstractOclBridge
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oclBridge_AbstractOclBridge_Dispose
  (JNIEnv *, jobject);

/*
 * Class:     oclBridge_AbstractOclBridge
 * Method:    OclMap
 * Signature: (Ljava/lang/String;[B[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_oclBridge_AbstractOclBridge_OclMap
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

/*
 * Class:     oclBridge_AbstractOclBridge
 * Method:    OclFilter
 * Signature: (Ljava/lang/String;[B[I)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_oclBridge_AbstractOclBridge_OclFilter
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

/*
 * Class:     oclBridge_AbstractOclBridge
 * Method:    OclReduce
 * Signature: (Ljava/lang/String;[B[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_oclBridge_AbstractOclBridge_OclReduce
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
