/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class serialization_SerializationBridge */

#ifndef _Included_serialization_SerializationBridge
#define _Included_serialization_SerializationBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     serialization_SerializationBridge
 * Method:    BackToBack
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_serialization_SerializationBridge_BackToBack
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     serialization_SerializationBridge
 * Method:    Print
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_serialization_SerializationBridge_Print
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     serialization_SerializationBridge
 * Method:    toString
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_serialization_SerializationBridge_toString
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     serialization_SerializationBridge
 * Method:    Adds
 * Signature: ([BB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_serialization_SerializationBridge_Adds
  (JNIEnv *, jclass, jbyteArray, jbyte);

#ifdef __cplusplus
}
#endif
#endif
